### ISSUE TITLE
(2020.06.21, 22:00, ZOOM) x-treme idea meeting

### ISSUE THREAD

**Issue by lucetre** [lucetre/x-treme#1]
### TODO

- [x] 아이디어 정하기
- [x] Balsamiq 각자 분담 기획
- [x] Github branch tutorial

**Comment by lucetre** [comment]
그림일기 - 사진 업로드를 해서 찍힌 날짜를 기준으로 날씨 보여주는

**Comment by zsoovely** [comment]
> 그림일기 - 사진 업로드를 해서 찍힌 날짜를 기준으로 날씨 보여주는

월별 캘린더에 날씨별 색깔 표시
흐림 - 회색
맑음 - 주황색
비옴 - 하늘색 etc

**Comment by lucetre** [comment]
과거 API: https://www.weather.go.kr/weather/climate/past_cal.jsp

**Comment by lucetre** [comment]
외국어 퀴즈 - 네이버 파파고 API
냉장고가 영어로? 무엇일지?

**Comment by lucetre** [comment]
영어 단어 외울 수 있는 게임 만들기
--> 주제 골라서 먼저 단어 목록(영어랑 한국어 뜻)보여주고, 몇 초 뒤에 한국어 뜻들이 떨어지면 막 그거에 맞는 영어 단어 쳐야 스테이지 클리어되는 거

Weather Picture Diary (Weather last): 날씨 그림일기, 과거 날씨 보여주기

**Comment by zsoovely** [comment]
날씨 관련 이름 후보
1. Weather last
2. Weather Record

**Comment by zsoovely** [comment]
산성비 말고 두더지 잡기처럼

**Comment by BlueLuxMea** [comment]
되나요
될까요
되나요
될까요
